### ISSUE TITLE
[BUG] Using a plus in an email results in an authorized transaction, but no order being created

### ISSUE THREAD

**Issue by erikhansen** [ParadoxLabs-Inc/authnetcim#11] opened 2024-11-18 20:57 UTC
# :bug: Bug report

## Current Behavior

In a guest checkout, if a user uses a plus (`+`) symbol in their email (e.g., `erik+123@example.com`), the Accept Hosted checkout process will fail. The user's credit card will be authorized, but the validation at this line… https://github.com/ParadoxLabs-Inc/authnetcim/blob/c556d14e04e09da80275cf9244d67cce9ba9de59/Observer/PaymentMethodAssignDataObserver.php#L204 …will cause the order to not be saved. The reason is that the `$transactionDetails->getData('customer_email')` function will return `erik 123@example.com`, since Authorize.net Accept Hosted apparently doesn't support `+` in a customer email.

![Checkout 2024-11-18 14-47-55](https://github.com/user-attachments/assets/1149a2f6-6500-47ad-9463-d1f4ef1c77b6)

## Expected Behavior

I can imagine several solutions to this problem:

1. Prevent `+` from being used for customer and/or checkout emails - This solution is not ideal since users have become accustomed to being able to use this email format (243 of the 204,647 customers in this client's DB are using a `+`)
2. Maybe Authorize.net Accept Hosted supports some sort of encoding (such as url encoding `+` to `%2B`) that would allow us to use `+` symbols
3. Change the extension so that everything between a `+` and an `@` symbol in an email is stripped before sending it to Authorize.net, and then change the validation check to compare that stripped down email. The downside to this approach is that users will receive emails from Authorize.net at an email that is different from what they provided.

## Minimal reproduction of the problem with instructions
See above for details.

## Environment

Authnetcim version: 2.4.4
Magento version: Adobe Commerce 2.4.4-p11
PHP version: 8.1

**Comment by erikhansen** [comment] 2024-11-18 20:58
@rhoerr We just encountered this issue in pre-launch testing. I'm curious if you have a solution/recommendation for this? Only 0.1% of customers use `+`, so we are fine with a simple solution.

**Comment by rhoerr** [comment] 2024-11-18 21:00
Hi @erikhansen! Thanks for reporting. Could you try this out? https://github.com/ParadoxLabs-Inc/authnetcim/commit/5392e9d6a9190c9881bfabfeebc46ef90c1fad83

We're not clear why this has only recently started. Seems like a regression on Authorize.net's side, or possibly a bug with their getTransactionDetails endpoint.

A space character is not valid for emails, so changing any encountered spaces to + in the details response seems like a safe operation.

**Comment by erikhansen** [comment] 2024-11-18 21:02
@rhoerr Man, you're always one step ahead. We'll try that out and report back, thanks.

**Comment by erikhansen** [comment] 2024-11-18 21:16
@rhoerr I hope this is an acceptable place to ask this follow-up question: for the orders that failed to be saved due to the validation in https://github.com/ParadoxLabs-Inc/authnetcim/blob/c556d14e04e09da80275cf9244d67cce9ba9de59/Observer/PaymentMethodAssignDataObserver.php#L204 would you expect that the authorization would be automatically voided? Based on [this article](https://support.paradoxlabs.com/support/solutions/articles/4000203045-authorize-net-cim-extra-authorizations-when-using-hosted-forms), it looks like _"We try to automatically void the transaction, but depending on the type of error this is not always possible."_ It seems like this would be a type of order that could be automatically voided.

![Authorize Net 2024-11-18 15-11-54](https://github.com/user-attachments/assets/788d4c3f-2654-4c9c-a395-f7d7ef5b77f5)

In case it's helpful, these are the extension settings:

![ Magento Admin 2024-11-18 15-14-49](https://github.com/user-attachments/assets/ca480b89-1e28-40b5-840f-52537fd85fd0)

**Comment by rhoerr** [comment] 2024-11-18 21:22
> @rhoerr I hope this is an acceptable place to ask this follow-up question: for the orders that failed to be saved due to the validation in ...

Will review in depth when time allows. The code that references is in TokenBase:
https://github.com/ParadoxLabs-Inc/tokenbase/blob/master/etc/events.xml#L26
which runs [Observer/CheckoutFailureVoidTransactionObserver.php](https://github.com/ParadoxLabs-Inc/tokenbase/blob/master/Observer/CheckoutFailureVoidTransactionObserver.php) upon `sales_model_service_quote_submit_failure`.

It could be that event doesn't trigger here, or any of the numerous conditions falls through.

**Comment by rhoerr** [comment] 2024-12-23 18:29
Hi Erik -- on review, we've decided to leave the validation/void handling as-is.

Validation errors do in fact bypass the 'void on error' code, because that only covers errors during `orderManagement->place()`, and the data import and validation happens prior to that. (`vendor/magento/module-quote/Model/QuoteManagement.php:422`)

The validation errors could be covered with void pretty easily, by wrapping the method call at `/ParadoxLabs/Authnetcim/Observer/PaymentMethodAssignDataObserver.php:163` and calling `$gateway->void($payment, $transactionId)` upon any error. However, this shouldn't _actually_ happen in normal usage. A validation error here means the transaction was declined, or we can't prove it was placed by the same customer, or the transaction time is too old. In this case it was a bug/discrepancy in email response, but we've fixed that so it shouldn't happen going forward.

If we did auto-void the referenced transaction on a transaction validation failure, we risk nefarious behavior like voiding/canceling payment for unrelated customers and orders. It's unlikely, but leaving the authorizations to time out on their own is the safer route.

So:

- [x] Email containing `+` fails to validate - Fixed in 5392e9d6a9190c9881bfabfeebc46ef90c1fad83 for next release
- [ ] Transaction validation fails to void on error - Won't fix

**Closed as completed by rhoerr** 2024-12-23 18:29 UTC
Labels: bug

**Comment by erikhansen** [comment] 2025-01-02 20:30
@rhoerr Thanks for looking into this and for your detailed reply.

>  However, this shouldn't _actually_ happen in normal usage.

The current homegrown Authorize.net Accept Hosted payment extension that our merchant is using has resulted in intermittent ghost orders (_captured_ (not authorized) payment with no order in Magento), so we have a script that runs and gets a list of payments from Authorize.net and compares them with the orders in Magento and emails us if there are any ghost orders found. We may modify this script to look for (un-voided) authorizations without associated captures so we can be alerted if this situation ever happens in the real world.

CC @kraken-chris
