### ISSUE TITLE
[BUG] Not able to do checkout with "Hosted iframe" option

### ISSUE THREAD

**Issue by dangtrinhtran** [ParadoxLabs-Inc/authnetcim#3] opened 2024-04-19 22:00 UTC
# :bug: Bug report

## Current Behavior

We upgrade Magento to 2.4.6-p5, paradoxlabs/authnetcim to 5.0.1 and then we are not able to do checkout with "Payment Form Type: Accept Hosted iframe".

## Expected Behavior

- It should validate the "Terms and Conditions" checkbox and the card form should be still there.

## Minimal reproduction of the problem with instructions

- Step 1: Enable "Payment Form Type: Accept Hosted iframe".
- Step 2: In Stores > Configuration > Sales > Checkout > Checkout Options > Enable Terms and Conditions: Yes
- Step 3: Do a test checkout with a shipping address and then go to the payment method step.
- Step 4: Check the checkbox "My billing and shipping address are the same".
- Step 5: Enter the card number but **DO NOT** check the checkbox "Terms and Conditions Information".
- Step 6: Click "Place Order" button.

<img width="897" alt="step__5" src="https://github.com/ParadoxLabs-Inc/authnetcim/assets/3252322/317015a7-a54e-475b-afb2-c448cdfdc07a">

=> The card form is gone and then get a receipt email from authorize.net but no order in Magento. There is no way to do next steps on the frontend.

<img width="927" alt="current_behavio" src="https://github.com/ParadoxLabs-Inc/authnetcim/assets/3252322/fc94fd7f-dd93-4757-9b5a-d0116ad364d8">

## Environment

<pre><code>
Authnetcim version: 5.0.1
Magento version: 2.4.6-p5
PHP version: 8.1 

Others:

</code></pre>

**Comment by rhoerr** [comment] 2024-04-22 12:35
Hi, thanks for reporting this and including the detailed steps to reproduce. The expected behavior is that the payment form shouldn't load until the term is accepted. We'll investigate.

**Comment by cdbessig** [comment] 2024-07-09 13:57
Just mentioning that we have this same issue!

**Comment by rhoerr** [comment] 2024-09-30 16:52
Thanks for the reports. A fix for this didn't make 5.1.1, but we are working on it.

**Comment by erikhansen** [comment] 2024-10-10 17:26
@rhoerr We are running into this issue on a client site. Do you happen to have a patch available for this?

**Comment by rhoerr** [comment] 2024-10-14 14:26
Thanks @erikhansen. No patch yet, but we have had it in progress. I'll prioritize this and tag everyone when we have a solution available.

**Comment by rhoerr** [comment] 2024-10-15 21:31
@erikhansen Tentative solution/patch for the T&C agreement, with standard checkout: https://github.com/ParadoxLabs-Inc/authnetcim/commit/f718f170581118689b7973c9d9eb9703e2613b10

It was tricky because of the inherent race condition of knockout component initialization vs child component rendering. Checking the terms and conditions validator too early will say they're valid even if they aren't.

I expect to release an update tomorrow with this fix.

**Comment by erikhansen** [comment] 2024-10-15 21:36
@rhoerr That was an impressively fast turnaround, thanks. We'll be looking for the release.

**Comment by rhoerr** [comment] 2024-10-16 20:06
This should be fixed in 5.1.2, available on composer now. https://github.com/ParadoxLabs-Inc/authnetcim/releases/tag/5.1.2

Please note if you use the Hyva Checkout compatibility module, we don't yet support agreements there. If you need it, please [open an issue there](https://github.com/ParadoxLabs-Inc/authnetcim-hyva-checkout) to note your interest.

**Closed as completed by rhoerr** 2024-10-16 20:06 UTC
Labels: bug
